# Generated by Django 3.1.2 on 2020-10-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EyeHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_abbr', models.CharField(max_length=2)),
                ('location_desc', models.CharField(max_length=150)),
                ('data_source', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('question', models.CharField(max_length=150)),
                ('response', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('race_ethnicity', models.CharField(max_length=150)),
                ('risk_factor', models.CharField(max_length=150)),
                ('risk_factor_response', models.CharField(max_length=150)),
                ('data_value_unit', models.CharField(max_length=150)),
                ('data_value_type', models.CharField(max_length=150)),
                ('data_value', models.CharField(max_length=150)),
                ('data_value_footnote_symbol', models.CharField(max_length=150)),
                ('data_value_footnote', models.CharField(max_length=150)),
                ('numerator', models.CharField(max_length=150)),
                ('topic_ID', models.CharField(max_length=150)),
                ('category_ID', models.CharField(max_length=150)),
                ('question_ID', models.CharField(max_length=150)),
                ('response_ID', models.CharField(max_length=150)),
                ('data_value_type_ID', models.CharField(max_length=150)),
                ('age_ID', models.CharField(max_length=150)),
                ('gender_ID', models.CharField(max_length=150)),
                ('race_ethnicity_ID', models.CharField(max_length=150)),
                ('risk_factor_ID', models.CharField(max_length=150)),
                ('risk_factor_response_ID', models.CharField(max_length=150)),
                ('geo_location', models.CharField(max_length=150)),
            ],
        ),
    ]
