# Generated by Django 3.1.2 on 2020-10-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201021_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyehealth',
            name='high_confidence_limit',
        ),
    ]
