# Generated by Django 3.1.2 on 2020-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_eyehealth_high_confidence_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyehealth',
            name='high_confidence_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyehealth',
            name='low_confidence_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
