# Generated by Django 3.1.5 on 2021-03-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201021_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesoIdade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=50)),
                ('codigo_uf', models.IntegerField()),
                ('uf', models.CharField(max_length=2)),
                ('codigo_ibge', models.CharField(max_length=6)),
                ('município', models.CharField(max_length=255)),
                ('PMB_quantidade', models.IntegerField()),
                ('PMB_porcentagem', models.FloatField()),
                ('PB_quatidade', models.IntegerField()),
                ('PB_porcentagem', models.FloatField()),
                ('PAE_quantidade', models.IntegerField()),
                ('PAE_porcentagem', models.FloatField()),
                ('PE_quantidade', models.IntegerField()),
                ('PE_porcentagem', models.FloatField()),
                ('total', models.IntegerField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='EyeHealth',
        ),
    ]
