# Generated by Django 3.1.7 on 2021-03-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210325_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesoidade',
            name='codigo_ibge',
            field=models.CharField(max_length=7),
        ),
    ]
