# Generated by Django 3.1.7 on 2021-03-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210326_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesoidade',
            name='codigo_ibge',
            field=models.IntegerField(),
        ),
    ]
